import os
import sys
import numpy as np
import pandas as pd


TARGET_COLUMN="Result"
PIPELINE_NAME="Network_Security"
ARTIFACT_DIR="Artifacts"
FILE_NAME="phisingData.csv"


TRAIN_FILE_NAME="train.csv"
TEST_FILE_NAME="test.csv"



DATA_INGESTION_COLLECTION_NAME:str="NETWORK_DATA"
DATA_INGESTION_DATABASE_NAME:str="NIKHIL"
DATA_INGESTION_DIR_NAME:str="DATA_INGESTION"
DATA_INGESTION_FEATURE_STORE_DIR:str="FEATURE_STORE"
DATA_INGESTION_INGESTED_DIR:str="INGESTED"
DATA_INGESTION_TRAIN_TEST_SPLIT:float=0.2



